services:
  postgres:
    image: postgres:13
    container_name: siak_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: siak
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d siak"]
      interval: 30s
      timeout: 10s
      retries: 5
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio
    restart: unless-stopped
    networks:
      - local-lakehouse
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - /tmp:/tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-client:
    image: minio/mc:RELEASE.2025-07-21T05-28-08Z-cpuv1
    depends_on:
      - minio
    networks:
      - local-lakehouse
    volumes:
      - /tmp:/tmp
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    entrypoint: >
      /bin/sh -c "
      until (mc alias set minio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      mc rm -r --force minio/lakehouse || echo '...rm ok...';
      mc mb minio/lakehouse || echo '...mb ok...';
      mc anonymous set public minio/lakehouse || echo '...set ok...';
      tail -f /dev/null
      "

networks:
  local-lakehouse:
    driver: bridge

volumes:
  postgres:
